user_age = [18, 19, 20, 21, 22]
print(user_age)
print(user_age[-1])
print(user_age[-2])
print(user_age[-3])
print(user_age[-4])
print(user_age[-5])
print(user_age[2:4])
print(user_age[0:5:2])
print(user_age[0:5:3])
print(user_age[:2])
print(user_age[1:])
